version: '3.9'
services:
  db:
    container_name: db-advisor
    image: postgres:15.0-alpine
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SCHEMA: public
    networks:
      - local

volumes:
  db_data:

networks:
  local:
    driver: bridge
