spring:
  application:
    name: advisor-api
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
server:
  port: 6060
